name: animerush
description: A new Flutter project.

# app pswd fo git
# ATBBBFdKzPzA3eBUTJrYKyzVYUunE1EC505A

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: 2.2.0
  animate_do: any
  sliver_header_delegate: ^0.0.5
  carousel_slider: ^4.2.1
  animations: ^2.0.7
  anim_search_bar: ^2.0.3
  google_nav_bar: ^5.0.6
  smooth_page_indicator: ^1.0.0+2
  rich_text_view: ^1.2.0
  better_player: ^0.0.83
  flutter_downloader: ^1.10.2
  path_provider: ^2.0.13
  permission_handler: ^10.2.0
  progress_dialog_null_safe: ^1.0.7
  intl: ^0.17.0
  http: ^0.13.5




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/icon1.png"


flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
  - family: Quicksand
    fonts:
      - asset: assets/font/Quicksand/Quicksand-Regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

