name: animerush
description: A new Flutter project.

# app pswd fo git
# ATBBBFdKzPzA3eBUTJrYKyzVYUunE1EC505A

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  google_fonts: ^4.0.4
  animate_do: ^3.0.2
  carousel_slider: ^4.2.1
  anim_search_bar: ^2.0.3
  google_nav_bar: ^5.0.6
  smooth_page_indicator: ^1.1.0
  rich_text_view: ^1.2.0
  better_player: ^0.0.83

#  find alternative
  flutter_downloader: ^1.10.4

  path_provider: ^2.0.15
  permission_handler: ^10.4.2
  progress_dialog_null_safe: ^1.0.7
  intl: ^0.18.1
  http: ^0.13.6
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.0
  get: ^4.6.5
  flutter_riverpod: ^2.3.6
  url_launcher: ^6.1.12
  package_info_plus: any
  flutter_jailbreak_detection: ^1.10.0
  flutter_secure_storage: ^8.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2


flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/icon1.png"


flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/icons/

  fonts:
  - family: Quicksand
    fonts:
      - asset: assets/font/Quicksand/Quicksand-Regular.ttf
      - asset: assets/font/Quicksand/Quicksand-Medium.ttf
      - asset: assets/font/Quicksand/Quicksand-Bold.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

