// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHWuICknyW4L49WU-YHt2yhk7AIgVqnRY',
    appId: '1:1044073376933:web:502dbae2f775581e1f714c',
    messagingSenderId: '1044073376933',
    projectId: 'animerush-f82f2',
    authDomain: 'animerush-f82f2.firebaseapp.com',
    storageBucket: 'animerush-f82f2.appspot.com',
    measurementId: 'G-YMHSXXNDBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN0Mz8z7CSLl9vRZTeSrRzRRlr7G7BAUc',
    appId: '1:1044073376933:android:2ce52f43db41a4811f714c',
    messagingSenderId: '1044073376933',
    projectId: 'animerush-f82f2',
    storageBucket: 'animerush-f82f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDoabR94eLyW1WkCaUCva9dy4P1gemqOQ',
    appId: '1:1044073376933:ios:7242f8a6f848927b1f714c',
    messagingSenderId: '1044073376933',
    projectId: 'animerush-f82f2',
    storageBucket: 'animerush-f82f2.appspot.com',
    iosBundleId: 'com.animerush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDoabR94eLyW1WkCaUCva9dy4P1gemqOQ',
    appId: '1:1044073376933:ios:7242f8a6f848927b1f714c',
    messagingSenderId: '1044073376933',
    projectId: 'animerush-f82f2',
    storageBucket: 'animerush-f82f2.appspot.com',
    iosBundleId: 'com.animerush',
  );
}
